config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "home#index"
  resources :searches
  resources :bibliotecas
  resources :refused_transfers
  resources :performed_transfers
  resources :transfers
  
  get 'searches/:id/edit', to: 'searches#edit', id: /[^\/]+/
  get 'searches/:id/edit', to: 'searches#edit', id: /\d{5}\.\d{3}\.\d\w/ 
  match '/searches/search' => 'searches#search', via: 'post'
  match '/searches/create' => 'searches#create', via: 'post'
  match '/searches/show' => 'searches#show', via: 'post'
  match '/transfers/teste' => 'transfers#teste', via: 'post'
  LOCALES = /en|pt\-BR/
    scope ":locale", locale: /en|pt\-BR/ do
      resources :users
      resources :searches
      resources :bibliotecas
      resources :refused_transfers
      resources :performed_transfers
      resources :transfers
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/views/home/index.html.erb
  <div class="authform">
    <div class="form-group">
    <% if user_signed_in? %>
        <tr>
        <td><%= link_to 'Pedir de transferência', searches_path, :id => "novos", :class => "btn btn-success" %></td>
        <td><%= link_to 'Novos pedidos', transfers_path, :id => "novos", :class => "btn btn-success" %></td>
        <td><%= link_to 'Pedidos indeferidos', refused_transfers_path, :id => "novos", :class => "btn btn-success" %></td>
        <td><%= link_to 'Pedidos deferidos', performed_transfers_path, :id => "novos", :class => "btn btn-success" %></td>
        </tr>
    <% else %>
        <td><%= link_to 'Cadastrar', new_user_registration_path, :class => "btn btn-success" %> ou <%= link_to 'Logar', new_user_session_path, :class => "btn btn-success"  %></td>
        </br></br><td><%= User.count %>  <%=t("Registered users")%></td>
    <% end %>
    </div> 
  </div> 