config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "home#index"
  resources :searches
  resources :bibliotecas
  resources :refused_transfers
  resources :performed_transfers
  resources :transfers
  
  get 'searches/:id/edit', to: 'searches#edit', id: /[^\/]+/
  get 'searches/:id/edit', to: 'searches#edit', id: /\d{5}\.\d{3}\.\d\w/ 
  match '/searches/search' => 'searches#search', via: 'post'
  match '/searches/create' => 'searches#create', via: 'post'
  match '/searches/show' => 'searches#show', via: 'post'
  match '/transfers/teste' => 'transfers#teste', via: 'post'
  LOCALES = /en|pt\-BR/
    scope ":locale", locale: /en|pt\-BR/ do
      resources :users
      resources :searches
      resources :bibliotecas
      resources :refused_transfers
      resources :performed_transfers
      resources :transfers
    end

end

app/models/search.rb
class Search < Autentication_transf
	self.table_name = "searches"
	self.primary_key = "id"
	#mount_uploader :my_file, FileUploader

	#validates_presence_of :search_matricula
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  before_action :user_signed_in?
  before_action :current_user
  before_action :user_session
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    # if aluno_existe?
    #   if aluno_possui_pendencia_na_biblioteca?
    #     flash[:notice] = 'Você não possui pendências na biblioteca, pode prosseguir.'
    #     turno_atual
    #     periodo_minimo
    #     @@matricula = params[:search_matricula]
    #   else
    #     flash[:notice] = 'Você possui pendências na biblioteca, não pode solicitar uma transferência antes de resolve-las..'
    #     redirect_to :back
    #   end
    # else
    #   flash[:notice] = 'Pasta inexistente, provavelmente você não é um aluno matriculado.'
    #   redirect_to :back
    # end
  end

  def show
  end

  #def new
  #end

# def new
#   @search = Search.new
#   @search = Search.new(params[:file])
#   @search.save
# end

  def create
    @gerar_pedido1 = Aluno.turno_atual_salvar(@@matricula).fetch(0).attributes
    @gerar_pedido2 = Turma.turma_disponivel_salvar(@@search_in_academico_periodo_atual.periodo_atual, @@search_in_academico_codigo_do_curso.cod_curso, @@search_in_academico_codigo_do_turno.cod_turno).fetch(0).attributes
    @hash_de_pedido = @gerar_pedido1, @gerar_pedido2
    @hash_unico_salvar = @hash_de_pedido.inject(:merge)
    @salvar = Search.new(@hash_unico_salvar)
    @salvar.save
    flash[:notice] = 'Pedido realizado com sucesso. Se desejar anexar uma justificativa para o pedido, acesse na tela inicial o menu Novos pedidos, mostrar pedido, pró e anexe sua justificativa.'
    render :index

  end

  def search
      if aluno_existe?
        if aluno_possui_pendencia_na_biblioteca?
          flash[:notice] = 'Você não possui pendências na biblioteca, pode prosseguir.'
          turno_atual
          periodo_minimo
          @@matricula = params[:search_matricula]
        else
          flash[:notice] = 'Você possui pendências na biblioteca, não pode solicitar uma transferência antes de resolve-las..'
          redirect_to :back
        end
      else
        flash[:notice] = 'Pasta inexistente, provavelmente você não é um aluno matriculado.'
        redirect_to :back
      end
  end

  #def destroy
    #@find.destroy
    #respond_with(@find)
  #end
  def aluno_existe?
    @search2 = Matricula.where(MATRICULA: (params[:search_matricula])).exists?
    #respond_to do |format|
      #format.html
      #format.json {render json: @search2}
    #end
  end

  def aluno_possui_pendencia_na_biblioteca?
    @search1 = Biblioteca.find_by(MATRICULA: params[:search_matricula], CONDICAO: params[:search_condicao])
  end

  def turno_atual
    @search_in_academico = Aluno.turno_atual(params[:search_matricula])
    puts params[:search_matricula]
  end

  def turno_disponivel
    #!@search_in_academico_ano_letivo_atual = Matricula.ano_letivo_atual(params[:search_matricula]).first
    @@search_in_academico_periodo_atual = Matricula.periodo_atual(params[:search_matricula]).first
    @@search_in_academico_codigo_do_curso = Matricula.codigo_do_curso(params[:search_matricula]).first
    @@search_in_academico_codigo_do_turno = Matricula.codigo_do_turno(params[:search_matricula]).first
    @search_in_academico3 = Turma.turma_disponivel(@@search_in_academico_periodo_atual.periodo_atual, @@search_in_academico_codigo_do_curso.cod_curso, @@search_in_academico_codigo_do_turno.cod_turno)
  end

  def periodo_minimo
    turno_disponivel
    @search_in_academico.each do |teste|
      if teste.PERIODO_ATUAL < 2
        flash[:notice] = "Você precisa estar pelo menos no 2º módulo para solicitar uma transferência"
        redirect_to :back
      end

      if teste.PERIODO_ATUAL >= 2 && @search_in_academico3 != []
        turno_disponivel
        render :show
      else @search_in_academico3 == []
          flash[:notice] = "Não existe um turno disponível para você no momento,
            então não poderá realizar um pedido de transferência"
          redirect_to :back
      end
    end
  end

  # private
  #   def set_search
  #     #@@file.my_file = params[:file]
  #   end

  #   def search_params
  #     params.require(:search).permit(:file)
  #   end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :my_file %>
    <%= f.file_field :my_file %>
    <%= f.submit%>
  </div>
<% end %>

app/views/searches/index.html.erb
<div class="authform">
  <h2>Verificação de Pendências</h2>
  <div class="form-group">
    <%= form_tag(searches_search_path, :method => :post) do %>
    <%= label_tag :MATRÍCULA %>
    <%= text_field_tag 'search_matricula', nil, placeholder: 'Insira aqui...',:autofocus => true, class: 'form-control' %>
    <p class='help'>
      Insira o número de matrícula contido na sua carteirinha de aluno.</p>
    <radio-button>
      <%= radio_button_tag 'search_condicao',false, :checked => true%>
    </radio-button>
    <%=submit_tag "Próximo", :class => 'btn btn-success'%>
    <% end %>
  </div>
</div>

app/views/searches/show.html.erb
<div class="panel panel-success">
  <div class="panel-heading">Dados da transferência</div>
  <div class="panel-body">
    <table class="table">
      <tbody>
        <h2>Atualmente em:</h2>
          <tr>
            <th>Nome do aluno</th>
            <th>Turno atual</th>
            <th>Turma atual</th>
          <tr>

          <tr>
            <% @search_in_academico.each do |search_in_academico| %>
              <td><%= search_in_academico.NOME_PESSOA %></td>
              <td><%= search_in_academico.DESC_TURNO %></td>
              <td><%= search_in_academico.DESC_TURMA %></td>
            <% end %>
          </tr>
      </tbody>
    </table>

    <table class="table">
      <tbody>
        <h2>TURMA DISPONÍVEL PARA TRANSFERÊNCIA</h2>
        <tr>
          <th>Nome da turma:</th>
          <th>Código da Turma:</th>
          <th>Turno:</th>
          <th>Curso:</th>
        </tr>

        <tr>
          <% @search_in_academico3.each do |search_in_academico3| %>
            <td><%= search_in_academico3.desc_turma %></td>
            <td><%= search_in_academico3.cod_turma %></td>
            <td><%= search_in_academico3.desc_turno %></td>
            <td><%= search_in_academico3.desc_curso %></td>
          <% end %>
        </tr>
      </tbody>
    </table>

      <td><%= form_tag "/searches/create" do %></td>
        <td><%= button_tag "Realizar Pedido", :class => 'btn btn-success'%></td>
      <% end %>
  </div>
</div>