config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "home#index"
  resources :searches
  resources :bibliotecas
  resources :refused_transfers
  resources :performed_transfers
  resources :transfers
  
  get 'searches/:id/edit', to: 'searches#edit', id: /[^\/]+/
  get 'searches/:id/edit', to: 'searches#edit', id: /\d{5}\.\d{3}\.\d\w/ 
  match '/searches/search' => 'searches#search', via: 'post'
  match '/searches/create' => 'searches#create', via: 'post'
  match '/searches/show' => 'searches#show', via: 'post'
  match '/transfers/teste' => 'transfers#teste', via: 'post'
  LOCALES = /en|pt\-BR/
    scope ":locale", locale: /en|pt\-BR/ do
      resources :users
      resources :searches
      resources :bibliotecas
      resources :refused_transfers
      resources :performed_transfers
      resources :transfers
    end

end

app/models/transfer.rb
class Transfer < Autentication_transf
	self.table_name = "searches"
	self.primary_key = "id"
	mount_uploader :my_file, FileUploader

	#validates_presence_of :justificativa
	#validates :COD_ALUNO, uniqueness: true
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_signed_in?
  before_action :current_user
  before_action :user_session
  before_action :set_transfer, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
      @transfers = Transfer.page(params[:page]).per(15).where(aceita: nil)
      respond_to do |format|
        format.html
        format.xml {render xml: @transfers}
        format.json {render json: @transfers}
      end
  end

  def show
    respond_with(@transfer)
  end

  def new
    #@transfer = Transfer.new
    #respond_with(@transfer)
  end

  def edit
  end

  def create
    @transfer = Transfer.new(transfer_params)
    @transfer.save
    respond_with(@transfer)
  end

  def update
    puts "OLHA, ESTOU AQUI PORRA!!!"
    puts transfer_params[:aceita]
    if transfer_params[:aceita] == "true"
      @dados2 = Matricula.transferencia(@@var.COD_TURNO, @@var.COD_TURMA, @@var.COD_ALUNO)
      @transfer.update(transfer_params)
      #respond_with(@transfer)
      flash[:notice] = "Tranferência realizada com sucesso."
      redirect_to '/transfers'
    end
      
    if transfer_params[:aceita] == "false"
      @transfer.update(transfer_params)
      flash[:notice] = "Pedido negado com sucesso."
      redirect_to '/transfers'
    end

    if transfer_params[:aceita] == nil
      @transfer.update(transfer_params)
      flash[:notice] = "justificativa anxada com sucesso."
      redirect_to '/transfers'
    end
  end

  # def update2
  #   @transfer = Transfer.update(params[:file])
  #   render :edit
  # end

  def destroy
    @transfer.destroy
    respond_with(@transfer)
  end

  private
    def set_transfer
      @transfer = Transfer.find(params[:id])
      @@var = @transfer
      @dados3 = Turma.alunos_por_turma(@@var.COD_TURMA).count
    end

    def transfer_params
      params.require(:transfer).permit(:COD_TURNO, :COD_TURMA, :COD_ALUNO, :justificativa, :aceita, :cond, :my_file)
    end
end

app/views/transfers/_form.html.erb
<%= form_for(@transfer) do |f| %>
  <div class="panel panel-success">
    <div class="panel-heading">Confirmação de pedido</div>
    <div class="panel-body">
      <table class="table">
          <% if @transfer.errors.any? %>
            <div id="error_explanation">
              <p><%= pluralize(@transfer.errors.count, "error") %> prohibited this transfer from being saved:</p>
              <ul>
              <% @transfer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        <%if current_user.admin?%>
          <div class="field">
            <%= f.label :COD_ALUNO %><br>
            <%= f.number_field :COD_ALUNO, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :NOME_PESSOA %><br>
            <%= f.text_field :NOME_PESSOA, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :DESC_TURNO %><br>
            <%= f.text_field :DESC_TURNO, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :PERIODO_ATUAL %><br>
            <%= f.text_field :PERIODO_ATUAL, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :COD_TURMA %><br>
            <%= f.text_field :COD_TURMA, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :desc_turno %><br>
            <%= f.text_field :desc_turno, :disabled => true, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label :COD_TURNO %><br>
            <%= f.text_field :COD_TURNO, :disabled => true, class: 'form-control' %>
          </div>
        <% end %>
        <%if current_user.admin?%>
          <div class="field">
            <%= f.label :Justificativa_do_coordenador %><br>
            <%= f.text_area :justificativa, class: 'form-control' %>
          </div>
          <div class="field">
            <%= f.label "Sim" %>
            <%= f.radio_button(:aceita, true)%>
            <%= f.label "Não" %>
            <%= f.radio_button(:aceita, false)%><br>
          </div>
          <div class="authform">
            <td><input type="checkbox" name='um_checkbox' id='um_checkbox' value="1">
            <%= f.button 'Confirmar transferência', :id => "submit_button", :class => "btn btn-success", disabled: 'true'%></td>
          </div>

          <script>
            $(function(){
              $('#um_checkbox').on('change', function(){
                if($(this).is(':checked')){
                  $('#submit_button').prop('disabled', false);
            }
            else{
              $('#submit_button').prop('disabled', true);
              }
            });
          });
          </script>
        <% end %>
        <%unless current_user.admin? %>
          <div class="field">
            <%= f.label :Anexar_arquivo %>
            <%= f.file_field :my_file, class: 'form-control' %></br>
            <%= f.button "OK", :class => 'btn btn-success'%>
          </div>   
        <%end%>               
      </table>
    </div>
  </div>
<% end %>

app/views/transfers/edit.html.erb
<%= render 'form' %>

<!--<%= link_to 'Show', @transfer %> |-->
<!--<%= link_to 'Back', transfers_path %>-->

app/views/transfers/index.html.erb
<!--<%= form_tag "/transfers/index" do %>-->
  <!--<radio-button>-->
    <!--<%= radio_button_tag :cond, false, :checked => true%>-->
  <!--</radio-button>-->
<!--<% end %>-->
<div class="kaminari">
  <%= paginate @transfers %>
</div>

<div class="panel panel-success">
  <div class="panel-heading">Pedidos de Tranferência</div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Nome pessoa</th>
          <th>Desc turno &nbsp; &nbsp;</th>
          <th>Periodo atual</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transfers.each do |transfer| %>
          <tr>
            <td><%= transfer.NOME_PESSOA %></td>
            <td><%= transfer.DESC_TURNO %></td>
            <td>&nbsp; &nbsp;<%= transfer.PERIODO_ATUAL %></td>
            <td>&nbsp; &nbsp;<%= link_to 'Mostrar pedido', transfer, :class => 'btn btn-success' %></td>

            <%if current_user.admin?%>
              <td><%= link_to 'Visualizar justificativa', transfer.my_file_url, :target => "_blank", :class => 'btn btn-success'%><td>
            <%end%>
            <!--<td><%= link_to 'Mostrar pedido', edit_transfer_path(transfer) %></td>-->
            <!--<td><%= link_to 'Destroy', transfer, method: :delete, data: { confirm: 'Tem certeza?' } %></td>-->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <!--<%= link_to 'New Transfer', new_transfer_path %>-->
    
  </div>
</div>

<div class="kaminari">
  <%= paginate @transfers %>
</div>

app/views/transfers/show.html.erb
<div class="panel panel-success">
  <div class="panel-heading">Dados da transferência</div>
  <div class="panel-body">
    <table class="table">
      <tbody>
        <h2>De:</h2>
          <tr>
            <th>Nome do aluno</th>
            <th>Descrição do turno</th>
            <th>Período atual</th>
            <th colspan="3"></th>
          </tr>
          <tr>
            <td><%= @transfer.NOME_PESSOA %></td>
            <td><%= @transfer.DESC_TURNO %></td>
            <td><%= @transfer.PERIODO_ATUAL %></td>
          </tr>
      </tbody>
      </table>

    <table class="table">
      <tbody>
        <h2>Para:</h2>
          <tr>
            <th>Código da turma</th>
            <th>Descrição do turno</th>
            <th>Periodo atual</th>
            <th>Quantidade de alunos na turma</th>
            <th colspan="3"></th>
          </tr>
          <tr>
            <td><%= @transfer.COD_TURMA %></td>
            <td><%= @transfer.desc_turno %></td>
            <td><%= @transfer.PERIODO_ATUAL %></td>
            <td><%= @dados3%></td>
          </tr>
      </tbody>
    </table>

    <div class="authform">
      <td><%= link_to 'Próximo', edit_transfer_path(@transfer), :class => "btn btn-success"%></td>
      <td><%= link_to 'Voltar', transfers_path, :class => "btn btn-success"%></td>
    </div>
  </div>
</div>